# Generated by Django 4.2.7 on 2023-12-08 13:49

from django.db import migrations


def create_groups(apps, schema_migration):
    User = apps.get_model('authentication', 'User')
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')

    add_ticket = Permission.objects.get(codename='add_ticket')
    change_ticket = Permission.objects.get(codename='change_ticket')
    delete_ticket = Permission.objects.get(codename='delete_ticket')
    view_ticket = Permission.objects.get(codename='view_ticket')

    add_review = Permission.objects.get(codename='add_review')
    change_review = Permission.objects.get(codename='change_review')
    delete_review = Permission.objects.get(codename='delete_review')
    view_review = Permission.objects.get(codename='view_review')

    creator_permissions = [
        add_ticket,
        change_ticket,
        delete_ticket,
        view_ticket,
        add_review,
        change_review,
        delete_review,
        view_review,
    ]

    creators = Group(name='creators')
    creators.save()
    creators.permissions.set(creator_permissions)

    subscriber_permissions = [
        view_ticket,
        view_review,
        add_review,
        change_review,
        delete_review,
    ]

    subscribers = Group(name='subscribers')
    subscribers.save()
    subscribers.permissions.set(subscriber_permissions)

    for user in User.objects.all():
        if user.role == 'CREATOR':
            creators.user_set.add(user)
        if user.role == 'SUBSCRIBER':
            subscribers.user_set.add(user)


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_groups),
    ]
