# Generated by Django 4.2.7 on 2023-12-08 13:50

from django.db import migrations


def assign_permissions(apps, schema_migration):
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')

    add_ticket = Permission.objects.get(codename='add_ticket')
    change_ticket = Permission.objects.get(codename='change_ticket')
    delete_ticket = Permission.objects.get(codename='delete_ticket')
    view_ticket = Permission.objects.get(codename='view_ticket')

    add_review = Permission.objects.get(codename='add_review')
    change_review = Permission.objects.get(codename='change_review')
    delete_review = Permission.objects.get(codename='delete_review')
    view_review = Permission.objects.get(codename='view_review')

    creators = Group.objects.get(name='creators')
    creators.permissions.add(add_ticket)
    creators.permissions.add(change_ticket)
    creators.permissions.add(delete_ticket)
    creators.permissions.add(view_ticket)
    creators.permissions.add(add_review)
    creators.permissions.add(change_review)
    creators.permissions.add(delete_review)
    creators.permissions.add(view_review)

    subscribers = Group.objects.get(name='subscribers')
    subscribers.permissions.add(view_ticket)
    subscribers.permissions.add(view_review)
    subscribers.permissions.add(add_review)
    subscribers.permissions.add(change_review)
    subscribers.permissions.add(delete_review)


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0002_auto_20231208_1349"),
    ]

    operations = [
        migrations.RunPython(assign_permissions),
    ]
